/**
 * Manejo de errores
 */

// try ..catch

// try{
//     // codigo
// } catch( error ){

// }

try{
    alert('Inicio del intento')
    
    unaVariable;

    alert('FIn del intento')
} catch( error ){
    alert('Atenci√≥n ocurrion un error')
} finally {
    alert('Se ha ejecutado el codigo')
}